name: chopper_authenticator_example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  chopper: ^7.0.5
  http: ^1.1.0

  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.3.8
  riverpod_annotation: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  custom_lint: ^0.5.2
  riverpod_lint: ^2.0.1

  build_runner: ^2.4.6
  riverpod_generator: ^2.2.6
  chopper_generator: ^7.0.2

flutter:
  uses-material-design: true
